import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>DIO Users API 🐲</h1>
        Visite a página{" "}
        <Link
          href={
            "https://dio-users.appspot.com/api/v1/skills?username=pedro_h_teles"
          }
        ></Link>
        <Image
          src="/skills-example.svg"
          alt="Skills Example"
          width={300}
          height={300}
        />
        A descrição do projetoe está no{" "}
        <Link href={"https://github.com/Pitossomo/dio-users-api"}>
          repositório do Github
        </Link>
      </main>
    </>
  );
}
